version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vignich
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

volumes:
  postgres_data:
